### ISSUE TITLE
README is missing

### ISSUE THREAD

**Issue by tusikalanse** [Hu-chi/Retrieval-Based-Chatbot#1]
please add README.md

**Comment by Hu-chi** [comment]
README.md will be provided until we complete tests on vector quantization.
![4CC094B0182D33C3CF4E63C844AA2F73](https://user-images.githubusercontent.com/25957211/101597660-fc8f7280-3a31-11eb-9cc2-46038a7ea090.jpg)

**Comment by Hu-chi** [comment]
README is provided now.
